#!/bin/bash
### BEGIN INIT INFO
# Provides:          dumpscribe-web
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: psy running dumpscribe-web
# Description:       dumpscribe-web is a web interface for dumpscribe https://github.com/CounterCultureLabs/dumpscribe
### END INIT INFO
#

# Source function library.
. /lib/lsb/init-functions

unmuddleDir="/home/dumpscribe/unmuddle"
logFile="/var/log/dumpscribe-web.log"

user="dumpscribe" # run as this user
command="/usr/local/bin/node"
appName="dumpscribe-web"
nodeApp="/var/www/dumpscribe/web/index.js"
runnerApp="/usr/local/bin/psy"
workingDir="/var/www/dumpscribe/web"

start() {

   echo "Starting $nodeApp"

   # Notice that we change the PATH because on reboot
   # the PATH does not include the path to node.
   PATH=/usr/local/bin:$PATH

   cd $workingDir
   su $user -c "$runnerApp start --logfile $logFile --name $appName -- $command $nodeApp $unmuddleDir"
   RETVAL=$?
}
restart() {
   echo "Restarting $appName"
   su $user -c "$runnerApp restart $appName"
   RETVAL=$?
}

stop() {
   echo "Shutting down $appName"
   su $user -c "$runnerApp stop $appName"
   RETVAL=$?
}

status() {
   echo "Status $appName"
   su $user -c "$runnerApp list"
   RETVAL=$?
}

case "$1" in
   start)
        start
        ;;
    stop)
        stop
        ;;
   status)
        status
       ;;
   restart)
        restart
        ;;
        *)
       echo "Usage:  {start|stop|status|restart}"
       exit 1
        ;;
esac
exit $RETVAL

